### PR TITLE
iterate in any DB object/array and get multidb query

### LINKED ISSUE #28: Support mutiple database instances
after a hard comparison between the two profiler addon for codeigniter, forensics are the better by so far! forensics handle and show many more date rether thatn others "complex addons"

if i have multi db instances in controller profiler forensics does not handle any db output, code example:

```
class Welcome extends CI_Controller
{
    public function index()
    {
        $this->DB1 = $this->load->database('development', TRUE);
        $this->DB2 = $this->load->database('development2', TRUE);

        $this->DB1->select('*');
        $result1 = $this->DB1->result();

        $this->DB2->select('*');
        $result2 = $this->DB2->result();
    }
}
```

there's some way to handle multi DB instances and show the querys, i try some patches backported from CI 3 brand but no success!

### PR DESCRIPTION
**Pull request by mckaygerhard**
iterate inthe instance object CI and get any DB_CI object to show querys made on multiple loaded databases... this close #28 and solves the problem of handlin multiple database

take in consideration the nex code:

1) in application/config
```
$config['sysdb'] =  array(
 'hostname'=>'localhost','username'=>'dbuser','password'=>'dbuserclave',
 'database'=>'', /* this will be changed "on the fly" in controler */
 'dbdriver'=>'mysqli','dbprefix'=>'',
 'pconnect'=>FALSE,'db_debug'=>TRUE,'cache_on'=>FALSE
 );
```
2) and next in controller:
```
  $configdbfly = $this->config->config['sysdb'];
  $configdbfly['database']='sysdbadminis'; /*cambiamos de db*/
  $this->load->database($configdbfly);
```

this change the DB on the fly..

But the patch include also show in wicht controller, due there's a filters plugin for codeigniter.. filter can take url controller invocation, pass to anther,, make querys, and return to original controller, so this patch can able to show that behaviour

### CODE REVIEW

**Comment by mckaygerhard** [comment]
also this feature was added recently to the Core codeigniter profiler.. in CI3 and CI 4 versions.

**Comment by lonnieezell** [comment]
Looks good. Thanks. Sorry it took so long to get back to you, have been on a small vacation the last few days.

**Comment by mckaygerhard** [comment]
i have a question, in my CI the tabs Console and Ram when i click, contents are emtpy.. : 
* in RAM, the title display correctly total ram usage, but when click, the content does not show nothing
* in consolo, the title only display console, and content does not show any

searching on the code, i try to understand the behavior of console.. so its only display if i used explicy in controller?

and RAM, i assumed that only display total ram, due the "builder" does not iterate on each object for specific usage...?

**Comment by lonnieezell** [comment]
You do have to load the Console manually. Once loaded, though, check out [the readme](https://github.com/lonnieezell/codeigniter-forensics#forensics-logging) about the logging functionality with `Console::log` and `Console::log_memory` which adds stuff to those tabs.

**Pull request merged**
